service: service-name

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: qa
  region: us-east-1
  profile: veillance

package:
   patterns:
      - ./config/app_secret_public.pem
      - ./config/app_secret_private.pem
   exclude:
      - ./loader/node_modules/**
      - ./lib/node_modules/**
      - ./jobs/node_modules/**
      
functions:
  api:
    handler: lambda/monolith.handler